app:
  name: "BlogManagement"
  mode: "dev"
  port: 9877
  token_expiration: 8

database:
  driver: "sqlite"
  host: ""
  port: 0
  username: ""
  password: ""
  datasource: "blog_management"

log:
  level: "debug"   # debug / info / warn / error
  mode: "both"  #console / file / both
  file_path: "./logs"
  file_name: "app"
  max_size: 10   # 单个文件最大 10 MB
  max_backups: 20     # 最多保留 20 个旧文件
  max_age: 30        # 日志最多保存 30 天
  compress: true     # 是否压缩